#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Multi-language Absurd Apology Generator - Fun Edition"""

import random

LANG = {
    'vi': {
        'title': '🎪 MÁY TẠO LỜI XIN LỖI HÀI HƯỚC 🎪',
        'intro': 'Quên sinh nhật/kỷ niệm/buổi hẹn? Đừng lo! Máy này sẽ tạo lời xin lỗi vui nhất cho bạn!',
        'prompt': 'Nhấn ENTER để tạo (Ctrl+C để thoát): ',
        'reason_label': 'LÝ DO',
        'action_label': 'HÀNH ĐỘNG',
        'promise_label': 'LẦN SAU',
        'consequence_label': 'THỀ NẾU',
    },
    'en': {
        'title': '🎪 FUN APOLOGY GENERATOR 🎪',
        'intro': 'Forgot a birthday/anniversary/date? This machine will create the FUNNIEST apology for you!',
        'prompt': 'Press ENTER to generate (Ctrl+C to exit): ',
        'reason_label': 'REASON',
        'action_label': 'ACTION',
        'promise_label': 'NEXT TIME',
        'consequence_label': 'SWORN CONSEQUENCE',
    },
    'zh': {
        'title': '🎪 搞笑道歉生成器 🎪',
        'intro': '忘记了生日/纪念日/约会？这款机器会为你生成最搞笑的道歉！',
        'prompt': '按回车键生成（Ctrl+C退出）：',
        'reason_label': '理由',
        'action_label': '行动',
        'promise_label': '下次',
        'consequence_label': '誓言后果',
    },
    'ja': {
        'title': '🎪 お笑い謝罪ジェネレーター 🎪',
        'intro': '誕生日/記念日/デートのことを忘れましたか？この 기계が、一番面白い謝罪文を生成します！',
        'prompt': 'Enterキーで生成（Ctrl+Cで終了）：',
        'reason_label': '理由',
        'action_label': '行動',
        'promise_label': '次回',
        'consequence_label': '誓いの結果',
    }
}

DATA = {
    'vi': {
        'apology': [
            "Xin lỗi nha!", "Ơ hay!", "Hề hề!", "Bíp bíp!",
            "Ting ting!", "Oops!", "Hắc xì!", "Âu dô!",
            "Lạy bạn!", "Kính bạn!", "Hello!", "Hế hế hế!",
            "Bùm bùm!", "Plop plop!", "Tít tắp!", "Hip hip!",
            "Dàng dàng!", "Pịch pịch!", "Lộp xộp!", "Tẹt tẹo!",
            "Ối giời ơi!", "Trời ơi!", "Mèn đét ơi!", "Mama mia!",
            "Chết cha!", "Tèo rồi!", "Toang rồi!", "Xong phim!",
            "Ơ kìa!", "Á à!", "Hỡi ôi!", "Than ôi!",
            "Ô hô!", "A ha!", "Eo ôi!", "Ui chao!",
            "Trời đất!", "Chao ôi!", "Ôi dào!", "Khổ thân!",
            "Tội mình!", "Vô duyên!", "Đứt rồi!", "Đoảng quá!",
            "Hú hồn!", "Hú vía!", "Mèn ơi!", "Bà nội ơi!",
            "Ông bà ơi!", "Má ơi!", "Tía ơi!", "Bố ơi!",
            "Hỡi ơi!", "Lạy chúa!", "Thánh thần!", "Phật ơi!",
            "Bụt ơi!", "Ngọc hoàng!", "Thiên địa!", "Càn khôn!",
            "Hú u u!", "Tút tút!", "Bíp bíp bíp!", "Tẹt!",
            "Tóp tóp!", "Bụp!", "Chảnh!", "Chậc!",
            "Tặc lưỡi!", "Thở dài!", "Lắc đầu!", "Cười khổ!",
            "Mếu máo!", "Sụt sùi!", "Sướt mướt!", "Tủi thân!",
            "Bẽ bàng!", "Ngơ ngác!", "Bối rối!", "Lúng túng!",
            "Hổn hển!", "Ngượng quá!", "Ngại lắm!", "Sượng trân!",
            "Sai bét!", "Lỗi tè!", "Quê độ!", "Đứng hình!",
            "Cười trừ!", "Lè lưỡi!", "Ơ hờ!", "Hửm?",
            "Hả?", "Ủa?", "Ụa!", "Ày ày!",
            "Ấy ấy!", "Ô là la!", "Ầy ầy!", "Eo eo!"
        ],
        'reason': [
            "con chó nhà hàng xóm nó cắn cáp mạng", "mèo mình nó ngồi lên bàn phím 3 tiếng đồng hồ", "chim bồ câu nó bay vào phòng rồi đấm máy tính", "chuột nó cắn chuột máy tính",
            "rùa nhà mình nó đi quá chậm nên Wi-Fi cũng chậm theo", "cá vàng nhà bạn nó nhảy ra bồn tắm", "ếch ngoài nhà nó kêu 3 tiếng liên tục", "tivi nhảy quảng cáo đúng lúc mình định nhắn tin",
            "Facebook suggest đúng 1 bài viết siêu thú vị", "thằng bạn nó gửi meme urgent", "Windows update restart không hỏi", "Netflix autoplay ngay lúc quan trọng",
            "Discord nó hiện thông báo sai lúc", "mình bị lag vì mở quá nhiều tab Chrome", "dòng lệnh terminal nó treo không rõ lý do", "GitHub merge conflict đánh nhau với mình",
            "Docker nó build fail đúng lúc deadline", "Alexa tự động gọi cho người yêu cũ mình", "smart TV nó bất chợt phát nhạc 90s", "AI assistant nó bỗng dưng kể chuyện cười",
            "gió bão làm Wi-Fi đi xuyên tường kỳ lạ", "mặt trời quá chói nên không thấy điện thoại", "mưa lớn làm mình sợ bấm nút gửi", "tuyết phủ toàn bộ antena Wi-Fi",
            "sao chổi bay qua làm gián đoạn mạng", "ánh trăng quá u ám khiến mình buồn ngủ", "đám mây nó che mất tín hiệu vệ tinh", "người giao hàng bấm chuông sai lúc",
            "hàng xóm hát karaoke 3 tiếng liên tục", "mình bị ám ảnh bởi một quảng cáo nước ngọt", "tia sét đánh vào router nhà", "áp suất khí quyển thay đổi đột ngột",
            "máy khoan nhà bên khoan quá lâu", "âm thanh xây dựng làm mất tập trung", "chuông cửa nhà hàng xóm reo hoài không thôi", "clip âm thanh đang download mà mạng yếu",
            "Zoom call bất chợt lỗi tại thời điểm quan trọng", "máy in kêu to lúc mình gõ tin nhắn", "tủ lạnh mở cửa tự nhiên", "điều hòa đột nhiên phát tiếng lạ",
            "quạt máy rơi xuống bàn", "bóng đèn nháy liên tục lúc quan trọng", "loa Bluetooth bắt được tín hiệu cũ", "pin dự phòng chết đột ngột",
            "cáp sạc bị mèo cắn đứt", "ốc vít trên laptop bị lỏng", "chuột wireless hết pin ngay lúc đó", "bàn phím bất chợt hỏng 1 phím",
            "màn hình bắt đầu nhòe", "webcam bị nhện giăng tơ", "microphone bắt tiếng kỳ lạ", "lò vi sóng bắt đầu kêu lạ",
            "quạt trần quay quá to", "máy nước nóng kêu sòng sọc", "máy rửa bát phát âm thanh kỳ cục", "vòi nước nhỏ giọt liên tục",
            "bồn tắm phát tiếng lạ", "vòi sen tự bật", "cửa tủ tự động mở", "cửa nhà bất chợt kẹt",
            "cửa sổ tự gió vào", "cửa tủ quần áo bật ra", "bàn làm việc lung lay", "ghế xoay xoay tự nhiên",
            "giường kêu cọt kẹt bất chợt", "đèn cây nháy liên tục", "tủ sách có tiếng động lạ", "gương phản chiếu kỳ lạ",
            "cửa sổ rít lên", "mặt bàn nứt bất chợt", "sàn nhà phát tiếng kêu", "tường có tiếng động lạ",
            "trần nhà có tiếng cọt kẹt", "cầu thang phát tiếng kêu", "hành lang đột ngột tối", "cơn gió thổi mạnh qua cửa",
            "mưa đập mạnh ngoài cửa sổ", "sét gầm gừ ngoài trời", "gió thổi xé tai", "tuyết rơi dày đặc",
            "nắng chói lóa", "mây kéo tới đen kịt", "sương mù dày đặc", "có một con bướm bay qua màn hình",
            "chim hót lạ bên ngoài", "ong bay quanh cửa sổ", "kiến bò trên bàn", "gián chạy quanh phòng",
            "ruồi bay vây vít", "muỗi vo ve quanh tai", "nhện giăng tơ trên trần", "thằn lằn bò qua tường",
            "ếch nhảy vào phòng", "tất cả thiết bị crash cùng lúc", "mạng cả nước bị sập", "nhà cung cấp mạng có sự cố",
            "bão mặt trời làm nhiễu sóng", "modem nóng quá tự tắt", "máy tính nhiễm virus", "ổ cứng kêu lạch cạch"
        ],
        'action': [
            "mình đang nhảy moonwalk về phía bạn", "mình đang hát rap xin lỗi bạn", "mình đã tặng bạn một bức tranh vẽ chó", "mình đang làm toast với bơ và mứt cho bạn",
            "mình đã nấu một nồi mì tôm và mang đến cho bạn", "mình đang đội nón phi hành gia nói xin lỗi", "mình đã vẽ một bức chân dung đẹp nhất của bạn", "mình đang làm pizza bay đến nhà bạn",
            "mình đã nhảy ballet một mình trên sân thượng", "mình đang đọc thơ xin lỗi bằng giọng opera", "mình đã làm một chiếc drone chở hoa đến cho bạn", "mình đang trồng một cái cây mang tên bạn",
            "mình đã viết một bài hát về sự ngốc nghếch của mình", "mình đang làm yoga cân bằng trên một chân", "mình đã làm một con robot nói xin lỗi thay mình", "mình đang kể chuyện cười để xin lỗi bạn",
            "mình đã làm một video dance cover xin lỗi", "mình đang khiêu vũ với một cây nấm", "mình đang tạo một bức tượng cát hình bạn", "mình đang viết xin lỗi trên mặt trăng bằng laser",
            "mình đang nuôi 1000 chim bồ câu để chở lời xin lỗi", "mình đang nhảy múa với 99 vũ công khác", "mình đã thuê billboard ghi xin lỗi khắp phố", "mình đang nấu cơm cháy hình trái tim",
            "mình đang chạy vòng quanh hồ Tây", "mình đang viết xin lỗi bằng cánh hoa", "mình đã dùng 10 tấn sôcôla để viết lời xin lỗi", "mình đang nhảy squat 100 lần liên tục",
            "mình đã sáng tạo điệu nhảy với 47 động tác", "mình đang phát sáng mặt bằng sơn dạ quang", "mình đang hát xin lỗi bằng tiếng chim", "mình đã tạo hashtag viral #XinLoiBan",
            "mình đang xây đài kỷ niệm bằng que tăm", "mình đang làm phim 3 tiếng về sự ngốc của mình", "mình đã vẽ 100 bức tranh khác nhau", "mình đang đi bộ 10km tới nhà bạn",
            "mình đang diễn lại phim Titanic phiên bản xin lỗi", "mình đã ghi âm lời xin lỗi 100 lần", "mình đang viết xin lỗi bằng máy bay khói", "mình đã dạy 50 chú chó sủa thành lời xin lỗi",
            "mình đang nhảy múa với bộ đồ cừu bông", "mình đang chuẩn bị pháo hoa hình chữ xin lỗi", "mình đang xếp 10000 quân domino", "mình đang vẽ tranh xin lỗi trên mặt hồ",
            "mình đã tô màu 100 trang sách xin lỗi", "mình đang nhảy parkour qua phố cổ", "mình đang ngân nga bài xin lỗi", "mình đã in chữ xin lỗi lên áo phông",
            "mình đang làm bánh kem hình chữ xin lỗi", "mình đang chạy marathon mang bảng xin lỗi", "mình đã tạo bộ sưu tập meme xin lỗi", "mình đang chiếu xin lỗi lên các tòa nhà",
            "mình đang tổ chức tiệc xin lỗi", "mình đã viết xin lỗi trên 100 chiếc đĩa", "mình đang reo hò xin lỗi như cổ vũ bóng đá", "mình đang trang trí xe hình hoa xin lỗi",
            "mình đang xếp 100 ngọn nến thành chữ xin lỗi", "mình đang làm vòng tròn ánh sáng trên sân", "mình đang vẽ xin lỗi lên bầu trời bằng diều", "mình đang xếp chữ xin lỗi bằng hạt cát",
            "mình đang chạy quanh công viên với bảng xin lỗi", "mình đang xây lâu đài cát ghi tên bạn", "mình đang vẽ xin lỗi bằng đèn LED", "mình đã thu âm xin lỗi bằng 20 giọng khác nhau",
            "mình đang tổ chức lễ tưởng niệm cho lỗi sai", "mình đang biểu diễn xiếc xin lỗi", "mình đang đốt pháo bông hình chữ xin lỗi", "mình đang nặn tượng đất sét hình bạn",
            "mình đang dàn dựng nhạc kịch về lỗi sai", "mình đang xây tháp giấy xin lỗi", "mình đang vẽ tranh tường xin lỗi", "mình đang biểu diễn rối nước xin lỗi",
            "mình đang tạo triển lãm tranh xin lỗi", "mình đang làm phim hoạt hình ngắn xin lỗi", "mình đang sáng tác nhạc giao hưởng xin lỗi", "mình đang livestream xin lỗi 24/7",
            "mình đang chiếu đèn xin lỗi lên bầu trời", "mình đang tổ chức triển lãm nghệ thuật", "mình đang làm tiệc pháo hoa xin lỗi", "mình đang tổ chức festival xin lỗi",
            "mình đang xếp đèn hoa đăng trên sông", "mình đang làm bài thuyết trình xin lỗi", "mình đang biểu diễn ballet xin lỗi", "mình đang sơn tường nhà mình thành tranh xin lỗi",
            "mình đang dệt thảm hình chữ xin lỗi", "mình đang viết thư pháp xin lỗi", "mình đang khắc gỗ tên bạn", "mình đang đan len một chiếc khăn xin lỗi",
            "mình đang cắt giấy origami hình xin lỗi", "mình đang trang trí ban công thành bảng xin lỗi", "mình đang gói quà tặng kèm thư xin lỗi", "mình đang chuẩn bị bó hoa khổng lồ",
            "mình đang đem 100 viên kẹo tới nhà bạn", "mình đang vẽ tranh phấn trên vỉa hè", "mình đang thổi bong bóng hình chữ xin lỗi", "mình đang gấp giấy 1000 con hạc giấy",
            "mình đang chuẩn bị một video tổng hợp ảnh đẹp", "mình đang vẽ chibi bạn dễ thương", "mình đang làm playlist nhạc dễ thương cho bạn", "mình đang nướng một mẻ bánh quy hình tim"
        ],
        'promise': [
            "lần sau mình sẽ nhắc nhở cả thế giới", "mình sẽ đặt 10 cái báo thức", "mình sẽ viết lời nhắc lên tay bằng bút bi", "mình đã nhờ cún nhắc giúp mình",
            "mình sẽ nhắn tin bạn mỗi ngày, kể cả khi không có gì", "mình sẽ gửi bạn một con vẹt nhắc nhở", "mình sẽ thuê người đến nhắc nhở mình", "mình sẽ nhớ bằng cả trái tim, có thể lắm",
            "mình sẽ tattoo lời nhắc lên trán bằng henna", "mình sẽ dán post-it khắp nhà", "mình sẽ nhờ cả gia đình nhắc giúp", "mình sẽ lập spreadsheet theo dõi",
            "mình sẽ đặt nhạc chuông mỗi 5 phút", "mình sẽ viết vào tờ tiền để nhìn mỗi ngày", "mình sẽ nhờ Alexa nhắc mỗi sáng", "mình sẽ biến bạn thành widget trên điện thoại",
            "mình sẽ ghi âm lời nhắc và phát 24/7 ở nhà", "mình sẽ làm một video TikTok hàng ngày", "mình sẽ lập một nhóm Discord riêng", "mình sẽ tạo một bot AI chỉ để nhắc nhở",
            "mình sẽ khắc lời nhắc lên cây bút chì", "mình sẽ gửi email tự động mỗi ngày", "mình sẽ nhờ cả công ty gọi nhắc", "mình sẽ lập một bảng theo dõi cả năm",
            "mình sẽ học chữ Braille để khắc lời nhắc", "mình sẽ đặt reminder ở mọi góc phòng", "mình sẽ gọi FaceTime hàng ngày nhắc bạn", "mình sẽ làm podcast hàng tuần",
            "mình sẽ khắc reminder lên cục đá", "mình sẽ tạo QR code dẫn tới reminder", "mình sẽ gửi bạn quà có reminder bên trong", "mình sẽ viết reminder bằng bút khói",
            "mình sẽ làm bài rap về reminder", "mình sẽ tạo chiếc vòng tay reminder", "mình sẽ lập danh sách 100 cách nhắc nhở", "mình sẽ gửi bạn con chim mang theo reminder",
            "mình sẽ viết reminder lên tay mỗi sáng", "mình sẽ làm một game về reminder", "mình sẽ làm website nhắc nhở", "mình sẽ nhờ robot phát âm reminder",
            "mình sẽ in reminder lên áo phông", "mình sẽ dán reminder lên gương tắm", "mình sẽ đặt reminder làm hình nền", "mình sẽ tự nhắc trước gương hàng ngày",
            "mình sẽ làm nhạc chuông reminder", "mình sẽ set reminder làm background", "mình sẽ viết reminder lên cánh cửa", "mình sẽ dán reminder khắp tường",
            "mình sẽ nhắc bạn cùng giờ hàng ngày", "mình sẽ tạo ứng dụng reminder riêng", "mình sẽ vẽ reminder lên cát biển", "mình sẽ làm video nhắc nhở hàng ngày",
            "mình sẽ đăng story reminder liên tục", "mình sẽ lập nhóm chat chỉ để reminder", "mình sẽ đặt alarm bằng nhạc pop", "mình sẽ dịch reminder sang 100 ngôn ngữ",
            "mình sẽ làm lịch đếm ngược đến ngày", "mình sẽ gọi bạn mỗi sáng 7h", "mình sẽ gửi thư tay hàng tuần", "mình sẽ làm phong bì đặc biệt",
            "mình sẽ mua một cuốn sổ ghi nhớ", "mình sẽ ký giấy cam kết với bạn", "mình sẽ làm món ăn đặc biệt cho bạn", "mình sẽ tặng bạn một chiếc vòng tay",
            "mình sẽ viết thư tình xin lỗi", "mình sẽ học 100 ngôn ngữ để nói reminder", "mình sẽ hát reminder mỗi sáng", "mình sẽ sáng tác nhạc về reminder",
            "mình sẽ làm poster dán khắp nhà", "mình sẽ in reminder lên cốc nước", "mình sẽ in reminder lên bát đĩa", "mình sẽ thêu reminder lên quần áo",
            "mình sẽ làm chiếc hộp reminder", "mình sẽ quay video cam kết", "mình sẽ viết nhật ký về lời hứa", "mình sẽ làm bảng tường ghi lời hứa",
            "mình sẽ đeo vòng cổ reminder", "mình sẽ mang theo reminder mọi lúc", "mình sẽ ôm reminder khi ngủ", "mình sẽ học thuộc lòng reminder",
            "mình sẽ ghi nhớ reminder cả đời", "mình sẽ sống với reminder", "mình sẽ thở cùng reminder", "mình sẽ đắm mình trong reminder",
            "mình sẽ hòa nhập với reminder", "mình sẽ trở thành reminder sống", "mình sẽ vẽ reminder lên tay mỗi ngày", "mình sẽ làm reminder thành mục đích sống",
            "mình sẽ dành cả tâm trí cho reminder", "mình sẽ tôn thờ reminder như báu vật", "mình sẽ thiền với reminder mỗi sáng", "mình sẽ mơ về reminder mỗi đêm",
            "mình sẽ nghĩ về reminder liên tục", "mình sẽ kể reminder cho mọi người", "mình sẽ dạy cả nhà về reminder", "mình sẽ lan tỏa reminder khắp nơi",
            "mình sẽ làm reminder nổi tiếng", "mình sẽ viết reminder vào nhật ký", "mình sẽ giữ reminder mãi mãi", "mình sẽ bảo vệ reminder bằng mọi giá"
        ],
        'consequence': [
            "nếu quên, mình sẽ tặng bạn một con capybara", "nếu quên lần nữa, bạn được quyền đánh mình bằng gối", "nếu quên, mình sẽ phải hát một bài trước đám đông", "nếu quên, mình sẽ public confession trên mạng xã hội",
            "nếu quên, mình sẽ thuê một billboard ghi sinh nhật bạn", "nếu quên, mình sẽ phải nhảy cover dance 1 tiếng", "nếu quên, mình sẽ tặng bạn cả một vườn hoa", "nếu quên, bạn được quyền đổi nick mình thành 'Hư Ngư'",
            "nếu quên, mình sẽ phải ăn hết một bát kem", "nếu quên, mình sẽ phải cosplay nhân vật anime công khai", "nếu quên, mình sẽ phải nói lời thật lòng trên stage", "nếu quên, bạn được quyền đổi avatar mình thành ảnh em bé",
            "nếu quên, mình sẽ phải đi giày của bạn 1 ngày", "nếu quên, mình sẽ phải xóa hết history duyệt web", "nếu quên, mình sẽ đi quanh phố với tấm bảng xin lỗi", "nếu quên, mình sẽ gửi 100 trang xin lỗi viết tay",
            "nếu quên, bạn có quyền khóa Facebook mình 1 tháng", "nếu quên, mình sẽ mặc đồ ngộ nghĩnh đi sự kiện", "nếu quên, mình sẽ dạy bạn code miễn phí", "nếu quên, mình sẽ đi bộ 10km quanh công viên",
            "nếu quên, bạn được xóa hết ảnh đẹp của mình", "nếu quên, mình sẽ làm việc nhà cho bạn 1 tuần", "nếu quên, mình sẽ viết 1000 lần 'mình xin lỗi'", "nếu quên, bạn được chọn quà tặng tùy ý",
            "nếu quên, mình sẽ đi vòng quanh nhà bạn", "nếu quên, mình sẽ thuê xe cổ hát xin lỗi", "nếu quên, bạn được quyền thách đố mình", "nếu quên, mình sẽ xuất hiện trên livestream bạn",
            "nếu quên, mình sẽ bỏ một bữa cơm ngon", "nếu quên, mình sẽ làm việc bạn bảo trong 1 ngày", "nếu quên, bạn được giả vờ không biết mình", "nếu quên, mình sẽ đứng cổng nhà bạn cả ngày",
            "nếu quên, mình sẽ ký tên trên bức tranh tự vẽ", "nếu quên, bạn được dùng hình mình làm avatar", "nếu quên, mình sẽ làm việc thiện nguyện 1 ngày", "nếu quên, mình sẽ không chơi điện thoại 1 tuần",
            "nếu quên, bạn được gọi điện cho bạn bè mình", "nếu quên, mình sẽ kiêng đồ ăn yêu thích 1 tuần", "nếu quên, mình sẽ làm việc vặt cho bạn 1 tuần", "nếu quên, mình sẽ mặc đồ sọc đi học",
            "nếu quên, bạn được đánh mình thêm gối lần nữa", "nếu quên, mình sẽ chúc bạn ngủ ngon mỗi đêm", "nếu quên, mình sẽ nghe bạn kể chuyện 1 tiếng", "nếu quên, mình sẽ làm trợ lý của bạn 1 ngày",
            "nếu quên, mình sẽ làm theo mọi lời bạn nói", "nếu quên, mình sẽ nấu cơm cho bạn 1 tuần", "nếu quên, mình sẽ rửa chén bát cho bạn", "nếu quên, mình sẽ giặt quần áo cho bạn",
            "nếu quên, mình sẽ quét nhà cho bạn", "nếu quên, mình sẽ lau bàn cho bạn", "nếu quên, mình sẽ tổng vệ sinh nhà bạn", "nếu quên, mình sẽ làm công việc bạn 1 ngày",
            "nếu quên, mình sẽ đi mua sắm hộ bạn", "nếu quên, mình sẽ đi chợ giúp bạn", "nếu quên, mình sẽ nấu món bạn thích", "nếu quên, mình sẽ rửa xe cho bạn",
            "nếu quên, mình sẽ cắt cỏ sân nhà bạn", "nếu quên, mình sẽ thay bóng đèn cho bạn", "nếu quên, mình sẽ sửa cửa hỏng cho bạn", "nếu quên, mình sẽ giúp bạn dọn nhà",
            "nếu quên, mình sẽ lắp kệ cho bạn", "nếu quên, mình sẽ ráp bàn ghế cho bạn", "nếu quên, mình sẽ trải giường cho bạn", "nếu quên, mình sẽ làm thiết kế hộ bạn",
            "nếu quên, mình sẽ giúp bạn lập kế hoạch", "nếu quên, mình sẽ tổ chức tủ đồ cho bạn", "nếu quên, mình sẽ lên lịch cho bạn", "nếu quên, mình sẽ làm bảng theo dõi cho bạn",
            "nếu quên, mình sẽ thuyết trình về bạn", "nếu quên, mình sẽ giải thích mọi điều bạn hỏi", "nếu quên, mình sẽ xin phép bạn mọi thứ", "nếu quên, mình sẽ khiêm tốn hơn",
            "nếu quên, mình sẽ học cách kiên nhẫn", "nếu quên, mình sẽ trở nên lạc quan", "nếu quên, mình sẽ thay đổi cách sống", "nếu quên, mình sẽ cải thiện bản thân",
            "nếu quên, mình sẽ học hỏi thêm", "nếu quên, mình sẽ tiến bộ mỗi ngày", "nếu quên, mình sẽ nâng cao kỹ năng", "nếu quên, mình sẽ hoàn thiện bản thân",
            "nếu quên, mình sẽ tự cải tổ", "nếu quên, mình sẽ đổi mới tư duy", "nếu quên, mình sẽ thành người tốt hơn", "nếu quên, mình sẽ sống có trách nhiệm",
            "nếu quên, mình sẽ trân trọng bạn hơn", "nếu quên, mình sẽ tặng bạn 100 đóa hồng", "nếu quên, mình sẽ mua bạn ly trà sữa", "nếu quên, mình sẽ dẫn bạn đi ăn nhà hàng",
            "nếu quên, mình sẽ chở bạn đi chơi cả ngày", "nếu quên, mình sẽ làm tài xế cho bạn 1 tuần", "nếu quên, mình sẽ tặng bạn quà bất ngờ", "nếu quên, mình sẽ gửi bạn một bưu thiếp",
            "nếu quên, mình sẽ vẽ chibi bạn dễ thương", "nếu quên, mình sẽ làm playlist nhạc cho bạn", "nếu quên, mình sẽ nướng bánh quy cho bạn", "nếu quên, mình sẽ làm sticker hình bạn",
            "nếu quên, mình sẽ chụp ảnh kỉ niệm cho bạn", "nếu quên, mình sẽ ghi video chúc mừng bạn", "nếu quên, mình sẽ viết bài thơ tặng bạn", "nếu quên, mình sẽ hát ru cho bạn ngủ"
        ]
    },
    'en': {
        'apology': [
            "Oops!", "Whoops!", "Woopsie!", "My bad!",
            "Ta-da!", "Behold!", "Eureka!", "Ta-daaa!",
            "Oh dear!", "Oopsie daisy!", "Woopsie poopsie!", "Pardon!",
            "Excuse me!", "Pardon my French!", "Oops a daisy!", "There it is!",
            "Ah-ha!", "Gosh!", "Dang it!", "Oh no!",
            "Good grief!", "Holy moly!", "Sheesh!", "Yikes!",
            "Crikey!", "Blimey!", "Cripes!", "Cor blimey!",
            "Good heavens!", "Stone the crows!", "Good Lord!", "Heavens above!",
            "For crying out loud!", "Oh my!", "Goodness gracious!", "My word!",
            "Oh boy!", "Oh brother!", "Oh snap!", "Whoa there!",
            "Hold up!", "Wait what!", "Hold the phone!", "Egads!",
            "Jeepers!", "Jiminy!", "Gee whiz!", "Holy cow!",
            "Holy smokes!", "Holy guacamole!", "Holy mackerel!", "Holy macaroni!",
            "Bless my soul!", "Heavens to Betsy!", "Land sakes!", "Lordy lordy!",
            "Mercy me!", "My stars!", "My goodness!", "My heavens!",
            "Goodness me!", "Bless me!", "Dear me!", "Oh dear me!",
            "Tut tut!", "Tsk tsk!", "Ay caramba!", "Mamma mia!",
            "Holy moley!", "Heavens to murgatroyd!", "Suffering succotash!", "Hot dog!",
            "Hot diggity!", "Well I never!", "Bless your heart!", "Oh fudge!",
            "Oh fiddlesticks!", "Phooey!", "Rats!", "Drat!",
            "Bother!", "Botheration!", "Confound it!", "Dagnabbit!",
            "Sweet heavens!", "Jumping jellybeans!", "Sufferin' cats!", "Great Scott!",
            "By Jove!", "Lawd have mercy!", "Heavens forfend!", "Bless us!",
            "Hark!", "Lo and behold!", "Forsooth!", "Verily!",
            "Egads and zounds!", "Zoinks!", "Jinkies!", "Gadzooks!"
        ],
        'reason': [
            "the neighbor's dog chewed the ethernet cable", "my cat sat on the keyboard for 3 hours", "a pigeon flew into my room and punched my computer", "a mouse chewed my computer mouse",
            "my turtle was too slow so my Wi-Fi got slow too", "your goldfish jumped out of the bathtub", "a frog outside croaked for 3 hours straight", "the TV autoplayed an ad at the exact moment I was typing",
            "Facebook suggested a super interesting post", "my friend sent an urgent meme", "Windows update restarted without asking", "Netflix autoplay kicked in at the crucial moment",
            "Discord showed a notification at the worst time", "I was lagging because I had too many Chrome tabs open", "the terminal command hung for unknown reasons", "GitHub merge conflict picked a fight with me",
            "Docker build failed right at the deadline", "Alexa accidentally called my ex", "the smart TV suddenly played 90s music", "the AI assistant randomly started telling jokes",
            "a storm made Wi-Fi travel through walls strangely", "the sun was too bright so I couldn't see my phone", "heavy rain made me afraid to press send", "snow covered my entire Wi-Fi antenna",
            "a comet flew by and disrupted the network", "the moon was too gloomy and made me sleepy", "a cloud blocked my satellite signal", "the delivery person rang at the worst time",
            "the neighbor sang karaoke for 3 hours straight", "I got obsessed with a soda commercial", "lightning struck my router", "atmospheric pressure changed suddenly",
            "the neighbor's drill ran too long", "construction noise destroyed my concentration", "the neighbor's doorbell rang endlessly", "I was downloading an audio clip on weak internet",
            "a Zoom call crashed at the critical moment", "the printer made loud noises while I was texting", "the fridge opened on its own", "the AC suddenly made a weird sound",
            "the fan fell onto the desk", "a light bulb flickered at the worst moment", "Bluetooth speaker picked up old signals", "the power bank died suddenly",
            "my charging cable got bitten by the cat", "a laptop screw came loose", "the wireless mouse died right then", "one keyboard key suddenly broke",
            "my monitor started getting blurry", "a spider made a web on my webcam", "the microphone picked up strange noises", "the microwave started making weird sounds",
            "the ceiling fan started spinning too loud", "the water heater made gurgling sounds", "the dishwasher made strange noises", "the faucet kept dripping",
            "the bathtub made weird sounds", "the shower turned itself on", "the cabinet door opened by itself", "the front door suddenly got stuck",
            "the window let wind in by itself", "the closet door swung open", "my desk started wobbling", "the swivel chair spun on its own",
            "the bed started creaking suddenly", "the lamp flickered constantly", "the bookshelf made strange sounds", "the mirror reflected weirdly",
            "the window started whistling", "the table surface cracked suddenly", "the floor made creaking sounds", "the wall had strange noises",
            "the ceiling started creaking", "the staircase made noise", "the hallway suddenly went dark", "a gust of wind blew through the door",
            "rain pounded outside the window", "thunder rumbled outside", "the wind whistled loudly", "snow fell densely",
            "the sun was blindingly bright", "dark clouds rolled in", "thick fog rolled in", "a butterfly flew across my screen",
            "birds chirped strangely outside", "bees buzzed around my window", "ants crawled on my desk", "a cockroach ran across the room",
            "flies swarmed around me", "mosquitoes buzzed in my ear", "a spider hung from the ceiling", "a lizard crawled across the wall",
            "a frog jumped into the room", "all my devices crashed at once", "the nationwide internet went down", "my ISP had an outage",
            "a solar storm interfered with signals", "the modem overheated and shut off", "my computer got a virus", "the hard drive started clicking"
        ],
        'action': [
            "I'm moonwalking towards you", "I'm rapping an apology song for you", "I gifted you a painting of a dog", "I'm making toast with butter and jam for you",
            "I cooked instant noodles and I'm bringing them to you", "I'm wearing a space helmet to say sorry", "I drew the most beautiful portrait of you", "I'm making pizza fly to your house",
            "I did ballet alone on the rooftop", "I'm reciting an apology poem in opera voice", "I made a drone carrying flowers for you", "I'm planting a tree with your name on it",
            "I wrote a song about my own silliness", "I'm doing yoga balancing on one leg", "I made a robot that says sorry for me", "I'm telling jokes to apologize",
            "I made a dance cover video as an apology", "I'm dancing with a mushroom", "I'm creating a sand sculpture of you", "I'm writing sorry on the moon with a laser",
            "I'm raising 1000 pigeons to carry my apology", "I'm dancing with 99 other dancers", "I rented billboards with sorry across town", "I'm cooking heart-shaped rice crisps",
            "I'm running around West Lake", "I'm writing sorry with flower petals", "I used 10 tons of chocolate to write sorry", "I'm doing 100 squats in a row",
            "I created a dance with 47 movements", "I'm glowing my face with neon paint", "I'm singing sorry in bird language", "I created a viral hashtag #SorryBuddy",
            "I'm building a memorial out of toothpicks", "I'm making a 3-hour movie about my silliness", "I painted 100 different paintings", "I'm walking 10km to your house",
            "I'm reenacting Titanic but it's about sorry", "I recorded sorry 100 times", "I'm writing sorry with a skywriting plane", "I taught 50 dogs to bark out my apology",
            "I'm dancing dressed as a fluffy sheep", "I'm preparing fireworks shaped like sorry", "I'm arranging 10000 dominoes", "I'm painting sorry on a lake's surface",
            "I colored 100 pages in a sorry coloring book", "I'm doing parkour through the old quarter", "I'm humming an apology tune", "I printed sorry on a t-shirt",
            "I'm making a cake shaped like sorry", "I'm running a marathon holding an apology sign", "I created a sorry meme collection", "I'm projecting sorry onto buildings",
            "I'm throwing a sorry party", "I wrote sorry on 100 plates", "I'm cheering sorry like at a soccer match", "I'm decorating a car with sorry flowers",
            "I arranged 100 candles into sorry", "I'm making a circle of light on the field", "I'm writing sorry in the sky with a kite", "I'm spelling sorry with sand",
            "I'm running around the park with a sorry sign", "I'm building a sandcastle with your name", "I'm drawing sorry with LED lights", "I recorded sorry in 20 different voices",
            "I'm holding a memorial for my mistake", "I'm performing a circus act of apology", "I'm setting off sorry-shaped fireworks", "I'm sculpting a clay statue of you",
            "I'm staging a musical about my mistake", "I'm building a paper tower of sorry", "I'm painting a sorry mural", "I'm performing water puppetry sorry",
            "I'm holding a sorry art exhibition", "I'm making a short animated sorry film", "I'm composing a sorry symphony", "I'm livestreaming sorry 24/7",
            "I'm beaming sorry into the sky", "I'm hosting an art exhibit", "I'm throwing a sorry fireworks party", "I'm organizing a sorry festival",
            "I'm floating lanterns down a river", "I'm giving a sorry presentation", "I'm performing sorry ballet", "I'm painting my own walls with sorry art",
            "I'm weaving a sorry carpet", "I'm doing sorry calligraphy", "I'm wood-carving your name", "I'm knitting a sorry scarf",
            "I'm folding origami spelling sorry", "I'm decorating my balcony with sorry signs", "I'm wrapping a gift with a sorry letter", "I'm preparing a huge bouquet",
            "I'm bringing 100 candies to your house", "I'm chalk-drawing on the sidewalk", "I'm blowing bubbles shaped like sorry", "I'm folding 1000 paper cranes",
            "I'm preparing a video photo montage", "I'm drawing a cute chibi of you", "I'm making you a wholesome playlist", "I'm baking heart-shaped cookies"
        ],
        'promise': [
            "next time I'll remind the entire world", "I'll set 10 alarms", "I'll write the reminder on my hand with a pen", "I asked my dog to remind me",
            "I'll text you every day even when there's nothing to say", "I'll send you a parrot that reminds you", "I'll hire someone to remind me", "I'll remember with my whole heart, maybe",
            "I'll henna-tattoo the reminder on my forehead", "I'll paste post-its all over the house", "I'll get my whole family to remind me", "I'll create a spreadsheet to track everything",
            "I'll set a ringtone every 5 minutes", "I'll write on bills so I see them daily", "I'll ask Alexa to remind me every morning", "I'll turn you into a widget on my phone",
            "I'll record the reminder and play it 24/7 at home", "I'll make a daily TikTok", "I'll create a private Discord group", "I'll build an AI bot just to remind me",
            "I'll carve the reminder on a pencil", "I'll send automatic emails daily", "I'll get my whole company to call and remind me", "I'll make a year-long tracking board",
            "I'll learn Braille to engrave the reminder", "I'll place reminders in every corner", "I'll FaceTime you daily to remind", "I'll make a weekly podcast",
            "I'll carve the reminder on a rock", "I'll create a QR code linking to the reminder", "I'll send you a gift with a reminder inside", "I'll write the reminder with a smoke pen",
            "I'll make a rap about the reminder", "I'll create a reminder bracelet", "I'll list 100 ways to remind", "I'll send you a bird carrying the reminder",
            "I'll write the reminder on my hand every morning", "I'll make a reminder game", "I'll build a reminder website", "I'll have a robot recite the reminder",
            "I'll print the reminder on a t-shirt", "I'll stick the reminder on my bathroom mirror", "I'll set the reminder as my wallpaper", "I'll remind myself in the mirror daily",
            "I'll make a reminder ringtone", "I'll set the reminder as background music", "I'll write the reminder on my door", "I'll paste the reminder all over the walls",
            "I'll remind you at the same time daily", "I'll create my own reminder app", "I'll draw the reminder on beach sand", "I'll make daily reminder videos",
            "I'll post reminder stories constantly", "I'll create a chat group just for reminders", "I'll set my alarm with pop music", "I'll translate the reminder into 100 languages",
            "I'll make a countdown calendar", "I'll call you every morning at 7am", "I'll send weekly handwritten letters", "I'll make a special envelope",
            "I'll buy a memory notebook", "I'll sign a written pledge with you", "I'll cook a special dish for you", "I'll give you a bracelet",
            "I'll write an apology love letter", "I'll learn 100 languages to say the reminder", "I'll sing the reminder every morning", "I'll compose music about the reminder",
            "I'll make posters all over the house", "I'll print the reminder on a cup", "I'll print the reminder on dishes", "I'll embroider the reminder on clothes",
            "I'll make a reminder box", "I'll film a video pledge", "I'll keep a promise diary", "I'll make a promise wall",
            "I'll wear a reminder necklace", "I'll carry the reminder everywhere", "I'll sleep hugging the reminder", "I'll memorize the reminder by heart",
            "I'll remember the reminder for life", "I'll live by the reminder", "I'll breathe with the reminder", "I'll immerse myself in the reminder",
            "I'll merge with the reminder", "I'll become a living reminder", "I'll draw the reminder on my hand daily", "I'll make the reminder my life purpose",
            "I'll devote all my mind to the reminder", "I'll treasure the reminder", "I'll meditate with the reminder daily", "I'll dream about the reminder nightly",
            "I'll think about the reminder constantly", "I'll tell everyone about the reminder", "I'll teach my whole family about it", "I'll spread the reminder everywhere",
            "I'll make the reminder famous", "I'll write the reminder in my diary", "I'll keep the reminder forever", "I'll guard the reminder with all I have"
        ],
        'consequence': [
            "if I forget, I'll gift you a capybara", "if I forget again, you can hit me with a pillow", "if I forget, I'll have to sing in front of a crowd", "if I forget, I'll publicly confess on social media",
            "if I forget, I'll rent a birthday billboard for you", "if I forget, I'll do a 1-hour dance cover", "if I forget, I'll gift you an entire flower garden", "if I forget, you may rename me 'Goof Master'",
            "if I forget, I'll eat a whole bowl of ice cream", "if I forget, I'll cosplay an anime character publicly", "if I forget, I'll say something heartfelt on stage", "if I forget, you may change my avatar to a baby photo",
            "if I forget, I'll wear your shoes for a day", "if I forget, I'll delete all my browsing history", "if I forget, I'll walk around with an apology sign", "if I forget, I'll send 100 handwritten apologies",
            "if I forget, you may lock my Facebook for a month", "if I forget, I'll wear silly clothes to events", "if I forget, I'll teach you coding for free", "if I forget, I'll walk 10km around the park",
            "if I forget, you may delete all my best photos", "if I forget, I'll do your chores for a week", "if I forget, I'll write 'I'm sorry' 1000 times", "if I forget, you may pick any gift",
            "if I forget, I'll circle your house", "if I forget, I'll hire a vintage car singing apologies", "if I forget, you may challenge me", "if I forget, I'll appear on your livestream",
            "if I forget, I'll skip a delicious meal", "if I forget, I'll do whatever you say for a day", "if I forget, you may pretend not to know me", "if I forget, I'll stand at your door all day",
            "if I forget, I'll sign my self-portrait", "if I forget, you may use my photo as your avatar", "if I forget, I'll do volunteer work for a day", "if I forget, I'll stay off my phone for a week",
            "if I forget, you may call all my friends", "if I forget, I'll skip my favorite food for a week", "if I forget, I'll do errands for you for a week", "if I forget, I'll wear striped pajamas to school",
            "if I forget, you may pillow-hit me again", "if I forget, I'll wish you goodnight every night", "if I forget, I'll listen to your stories for an hour", "if I forget, I'll be your assistant for a day",
            "if I forget, I'll follow your every word", "if I forget, I'll cook for you for a week", "if I forget, I'll wash your dishes", "if I forget, I'll do your laundry",
            "if I forget, I'll sweep your house", "if I forget, I'll wipe your tables", "if I forget, I'll deep-clean your house", "if I forget, I'll do your work for a day",
            "if I forget, I'll go shopping for you", "if I forget, I'll do your grocery run", "if I forget, I'll cook your favorite dish", "if I forget, I'll wash your car",
            "if I forget, I'll mow your lawn", "if I forget, I'll change your light bulbs", "if I forget, I'll fix your broken door", "if I forget, I'll help you tidy up",
            "if I forget, I'll mount your shelves", "if I forget, I'll assemble your furniture", "if I forget, I'll make your bed", "if I forget, I'll design things for you",
            "if I forget, I'll help plan your schedule", "if I forget, I'll organize your closet", "if I forget, I'll plan your calendar", "if I forget, I'll make tracking sheets for you",
            "if I forget, I'll present about you", "if I forget, I'll explain anything you ask", "if I forget, I'll ask for permission for everything", "if I forget, I'll be more humble",
            "if I forget, I'll learn patience", "if I forget, I'll become more optimistic", "if I forget, I'll change my lifestyle", "if I forget, I'll improve myself",
            "if I forget, I'll learn more", "if I forget, I'll grow daily", "if I forget, I'll level up my skills", "if I forget, I'll polish myself",
            "if I forget, I'll reform myself", "if I forget, I'll renew my mindset", "if I forget, I'll become a better person", "if I forget, I'll live more responsibly",
            "if I forget, I'll appreciate you more", "if I forget, I'll send you 100 roses", "if I forget, I'll buy you bubble tea", "if I forget, I'll take you to a restaurant",
            "if I forget, I'll spend a whole day with you", "if I forget, I'll drive for you for a week", "if I forget, I'll surprise you with a gift", "if I forget, I'll mail you a postcard",
            "if I forget, I'll draw you a cute chibi", "if I forget, I'll make you a playlist", "if I forget, I'll bake cookies for you", "if I forget, I'll make stickers of your face",
            "if I forget, I'll take memorial photos for you", "if I forget, I'll film a congrats video", "if I forget, I'll write you a poem", "if I forget, I'll sing you a lullaby"
        ]
    },
    'zh': {
        'apology': [
            "哎呀!", "哎呦!", "哈喽!", "哇哦!",
            "抱歉啦!", "不好意思!", "打扰了!", "请原谅!",
            "天哪!", "我的天!", "哎哟喂!", "哎哟妈!",
            "啊呀!", "哎嘛!", "哎哟!", "哎呦哎呦!",
            "啊!", "呀!", "哇!", "哈!",
            "哎吆!", "唉!", "哦!", "呃!",
            "嗯!", "哎哎哎!", "完蛋了!", "糟糕!",
            "糟了!", "坏了!", "完了!", "毁了!",
            "天啊!", "老天爷!", "上帝啊!", "佛祖啊!",
            "妈呀!", "爸呀!", "祖宗啊!", "苍天啊!",
            "哎呀我的妈!", "哎呀我的天!", "哎呀我的爸!", "哎呀我的娘!",
            "哎哟我的天!", "哎哟我的妈!", "哎哟我的爸!", "哎哟我的祖宗!",
            "呜呼!", "呜呼哀哉!", "悲哉!", "可怜!",
            "苦也!", "惨也!", "苦哉!", "惨哉!",
            "我去!", "我擦!", "我滴乖乖!", "我滴老天!",
            "乖乖!", "妈耶!", "我天!", "我娘!",
            "嘿!", "嘁!", "切!", "啧!",
            "啧啧!", "嘁切!", "啧切!", "唉哟!",
            "啊哈!", "嘿哟!", "哎哟!", "唉呀!",
            "呃啊!", "呃哇!", "呃呀!", "呃啊呀!",
            "妈妈咪呀!", "爹啊!", "娘啊!", "祖宗啊!",
            "哎哟喂哟!", "哎呀呀!", "哎呀呀呀!", "哎呀哎呀!",
            "哦豁!", "我滴!", "我可!", "我哎!",
            "呜啊!", "呜哇!", "呜呜!", "呃呃!",
            "啦啦!", "嘞嘞!", "了了!", "罢了!"
        ],
        'reason': [
            "邻居家的狗咬断了网线", "我的猫坐在键盘上3个小时", "鸽子飞进房间打了电脑", "老鼠咬坏了鼠标",
            "我家乌龟太慢所以Wi-Fi也慢", "你家金鱼跳出了浴缸", "外面青蛙叫了3小时不停", "电视在我打字时自动播放了广告",
            "Facebook推荐了一篇超有趣的文章", "朋友发来了紧急的表情包", "Windows更新没问就重启了", "Netflix在关键时刻自动播放",
            "Discord在最糟时刻弹通知", "我因为开了太多Chrome标签卡顿", "终端命令莫名其妙卡住", "GitHub合并冲突跟我打架",
            "Docker在截止日期前构建失败", "Alexa不小心打给了我前任", "智能电视突然放90年代音乐", "AI助手突然开始讲笑话",
            "暴风雨让WiFi穿墙怪怪的", "太阳太亮我看不见手机", "大雨让我害怕按发送键", "雪盖住了整个WiFi天线",
            "一颗彗星飞过中断了网络", "月亮太阴暗让我犯困", "云遮住了卫星信号", "快递员在最坏时刻按门铃",
            "邻居唱KTV唱了3小时", "我被一个饮料广告迷住了", "闪电击中了我的路由器", "气压突然变化",
            "邻居的电钻钻得太久", "建筑噪音让我分心", "邻居家门铃响个不停", "我在弱网上下载音频",
            "Zoom通话在关键时刻崩了", "打字时打印机响很大声", "冰箱门自己开了", "空调突然发奇怪的声音",
            "风扇掉到桌上", "灯泡在关键时刻闪烁", "蓝牙音响捕捉到旧信号", "充电宝突然没电了",
            "我的充电线被猫咬断了", "笔记本螺丝松了", "无线鼠标刚好没电了", "键盘突然一个键坏了",
            "我的显示器开始模糊", "蜘蛛在网络摄像头结网", "麦克风捕捉到奇怪声音", "微波炉开始发出奇怪声音",
            "吊扇转得太大声", "热水器咕嘟咕嘟响", "洗碗机发出怪声", "水龙头一直滴水",
            "浴缸发出怪声", "淋浴自己开了", "柜门自己打开了", "前门突然卡住了",
            "窗户自己进风", "衣柜门弹开了", "我的书桌开始摇晃", "转椅自己转了起来",
            "床突然吱吱响", "台灯一直闪", "书架发出奇怪声音", "镜子反射很奇怪",
            "窗户开始呼啸", "桌面突然裂了", "地板发出吱吱声", "墙壁有奇怪声音",
            "天花板开始吱吱响", "楼梯发出响声", "走廊突然变黑", "一阵风从门外吹进来",
            "雨打在窗外很响", "雷在外面咆哮", "风呼啸地刮", "雪下得很密",
            "太阳刺眼", "乌云密布", "雾气浓重", "一只蝴蝶飞过屏幕",
            "鸟在外面奇怪地叫", "蜜蜂在窗户附近飞", "蚂蚁在桌上爬", "蟑螂跑过房间",
            "苍蝇围着我转", "蚊子在耳边嗡嗡", "蜘蛛挂在天花板", "壁虎爬过墙",
            "青蛙跳进房间", "所有设备同时崩溃", "全国互联网瘫痪", "我的网络提供商出故障",
            "太阳风暴干扰信号", "调制解调器过热关机", "我的电脑感染病毒", "硬盘开始咔哒咔哒响"
        ],
        'action': [
            "我在用太空步走向你", "我在为你唱说唱道歉歌", "我送给你一幅狗狗画", "我在为你做黄油果酱吐司",
            "我煮了泡面正要送给你", "我戴着太空头盔说抱歉", "我画了你最美的肖像", "我让披萨飞到你家",
            "我在屋顶上独自跳芭蕾", "我在用歌剧嗓子朗诵道歉诗", "我做了载花的无人机给你", "我在种一棵刻有你名字的树",
            "我写了一首关于我傻气的歌", "我在单腿做瑜伽平衡", "我造了一个替我道歉的机器人", "我在讲笑话来道歉",
            "我做了道歉的舞蹈翻跳视频", "我在和蘑菇跳舞", "我在做你的沙雕", "我在用激光在月亮上写道歉",
            "我在养1000只鸽子送道歉", "我在和99个舞者一起跳舞", "我租了广告牌写道歉布满全城", "我在煮心形米花",
            "我在绕西湖跑", "我在用花瓣写道歉", "我用了10吨巧克力写道歉", "我在连续做100个深蹲",
            "我创造了47个动作的舞蹈", "我在用荧光漆让脸发光", "我在用鸟语唱道歉", "我创造了病毒话题#对不起朋友",
            "我在用牙签建造纪念碑", "我在做一部3小时关于我傻气的电影", "我画了100幅不同的画", "我在走10公里到你家",
            "我在重演泰坦尼克但内容是道歉", "我录了100次道歉", "我在用飞机烟雾写道歉", "我教了50只狗叫出我的道歉",
            "我穿着毛茸茸的羊装跳舞", "我在准备道歉形状的烟火", "我在排10000张多米诺骨牌", "我在湖面上画道歉",
            "我涂色了100页道歉涂色书", "我在老街区跑酷", "我在哼一首道歉曲", "我在T恤上印了道歉",
            "我在做道歉形状的蛋糕", "我在跑马拉松拿着道歉牌", "我做了道歉表情包合集", "我在把道歉投影到建筑上",
            "我在办道歉派对", "我在100个盘子上写了道歉", "我在像足球比赛一样欢呼道歉", "我在装饰一辆带道歉花的车",
            "我把100根蜡烛排成道歉", "我在场地上做光圈", "我用风筝在天上写道歉", "我在用沙子拼道歉",
            "我在绕公园跑举着道歉牌", "我在堆有你名字的沙堡", "我在用LED灯画道歉", "我用20种不同声音录了道歉",
            "我在为我的错误举办纪念", "我在表演马戏道歉", "我在放道歉形状的烟火", "我在塑造你的粘土像",
            "我在演关于错误的音乐剧", "我在建一座道歉纸塔", "我在画道歉壁画", "我在表演道歉水偶戏",
            "我在办道歉画展", "我在做道歉动画短片", "我在作道歉交响曲", "我在24/7直播道歉",
            "我在用光柱把道歉射向天空", "我在办画展", "我在办道歉烟火派对", "我在办道歉节",
            "我在河上放灯", "我在做道歉演讲", "我在表演道歉芭蕾", "我在自家墙上画道歉壁画",
            "我在织道歉毯子", "我在写道歉书法", "我在木雕你的名字", "我在织道歉围巾",
            "我在折拼道歉的折纸", "我在装饰阳台为道歉牌", "我在包裹带道歉信的礼物", "我在准备超大花束",
            "我把100颗糖果带到你家", "我在人行道上画粉笔画", "我在吹道歉形状的泡泡", "我在折1000只纸鹤",
            "我在做美照视频合集", "我在画你的可爱Q版", "我在为你做温馨歌单", "我在烤心形饼干"
        ],
        'promise': [
            "下次我会提醒整个世界", "我会设10个闹钟", "我会用笔写提醒在手上", "我已经叫狗狗提醒我了",
            "我每天都给你发信息哪怕没事", "我会送你只会提醒的鹦鹉", "我会雇人来提醒我", "我会用心记住，可能会",
            "我会用海娜在额头纹提醒", "我会把便利贴贴满整个家", "我会让全家人提醒我", "我会做表格跟踪一切",
            "我每5分钟设个铃声", "我会写在钱上每天看", "我会让Alexa每天早上提醒", "我会把你变成手机小部件",
            "我会录提醒在家24/7播放", "我会每天做一个TikTok", "我会建一个私人Discord群", "我会建AI机器人只为提醒我",
            "我会把提醒刻在铅笔上", "我会每天发自动邮件", "我会让全公司打电话提醒", "我会做全年跟踪板",
            "我会学盲文刻提醒", "我会在每个角落放提醒", "我会每天FaceTime提醒你", "我会做每周播客",
            "我会把提醒刻在石头上", "我会做二维码链接提醒", "我会送你带提醒的礼物", "我会用烟笔写提醒",
            "我会做关于提醒的说唱", "我会做提醒手链", "我会列100种提醒方式", "我会送你带提醒的鸟",
            "我每天早上在手上写提醒", "我会做提醒游戏", "我会建提醒网站", "我会让机器人念提醒",
            "我会在T恤上印提醒", "我会把提醒贴在浴室镜子上", "我会把提醒设为壁纸", "我每天在镜子前自我提醒",
            "我会做提醒铃声", "我会把提醒设为背景音乐", "我会在门上写提醒", "我会把提醒贴满墙",
            "我每天同一时间提醒你", "我会做自己的提醒app", "我会在沙滩上画提醒", "我每天做提醒视频",
            "我会一直发提醒故事", "我会建只为提醒的群聊", "我会用流行乐设闹钟", "我会把提醒翻译成100种语言",
            "我会做倒计时日历", "我每天早上7点给你打电话", "我会每周寄手写信", "我会做特别的信封",
            "我会买个记事本", "我会和你签书面承诺", "我会为你做特别菜", "我会送你手链",
            "我会写道歉情书", "我会学100种语言说提醒", "我每天早上唱提醒", "我会作关于提醒的曲",
            "我会贴海报满屋", "我会在杯子上印提醒", "我会在碗上印提醒", "我会在衣服上绣提醒",
            "我会做提醒盒子", "我会拍承诺视频", "我会写承诺日记", "我会做承诺墙",
            "我会戴提醒项链", "我会随身带提醒", "我会抱着提醒睡觉", "我会背下提醒",
            "我会一辈子记住提醒", "我会和提醒一起生活", "我会和提醒一起呼吸", "我会沉浸在提醒中",
            "我会和提醒融为一体", "我会成为活着的提醒", "我每天在手上画提醒", "我会让提醒成为我的人生目标",
            "我会把全部心思放在提醒上", "我会珍视提醒", "我每天和提醒冥想", "我每晚梦到提醒",
            "我会一直想着提醒", "我会告诉所有人提醒", "我会教全家人提醒", "我会让提醒传遍各处",
            "我会让提醒出名", "我会写提醒到日记里", "我会永远保留提醒", "我会用尽一切守护提醒"
        ],
        'consequence': [
            "如果我忘了，我送你一只水豚", "如果我再忘，你可以用枕头打我", "如果我忘了，我得在人群前唱歌", "如果我忘了，我会在社交媒体公开承认",
            "如果我忘了，我租广告牌祝你生日", "如果我忘了，我得跳1小时舞蹈翻跳", "如果我忘了，我送你整个花园", "如果我忘了，你可改我昵称为'蠢萌'",
            "如果我忘了，我得吃完一整碗冰淇淋", "如果我忘了，我得公开cosplay动漫角色", "如果我忘了，我得在舞台上说真心话", "如果我忘了，你可换我头像为婴儿照",
            "如果我忘了，我得穿你的鞋一天", "如果我忘了，我得删除所有浏览记录", "如果我忘了，我得举着道歉牌走街区", "如果我忘了，我寄你100页手写道歉",
            "如果我忘了，你可锁我Facebook一个月", "如果我忘了，我得穿傻气衣服去活动", "如果我忘了，我免费教你编程", "如果我忘了，我得走10公里绕公园",
            "如果我忘了，你可删我所有好照片", "如果我忘了，我得为你做家务一周", "如果我忘了，我得写1000遍'我错了'", "如果我忘了，你可挑任何礼物",
            "如果我忘了，我得绕你家跑", "如果我忘了，我租老车唱道歉", "如果我忘了，你可挑战我", "如果我忘了，我得出现在你直播",
            "如果我忘了，我得错过一顿美食", "如果我忘了，我得听你的话一天", "如果我忘了，你可假装不认识我", "如果我忘了，我得在你家门口站一天",
            "如果我忘了，我得在自画像上签名", "如果我忘了，你可用我照片做头像", "如果我忘了，我得做一天志愿服务", "如果我忘了，我得一周不玩手机",
            "如果我忘了，你可给我所有朋友打电话", "如果我忘了，我得一周不吃喜欢的食物", "如果我忘了，我得为你跑腿一周", "如果我忘了，我得穿条纹睡衣上学",
            "如果我忘了，你可再用枕头打我", "如果我忘了，我每晚祝你晚安", "如果我忘了，我得听你讲故事一小时", "如果我忘了，我得做你的助理一天",
            "如果我忘了，我得听你每一句话", "如果我忘了，我得为你做饭一周", "如果我忘了，我得为你洗碗", "如果我忘了，我得为你洗衣服",
            "如果我忘了，我得为你扫地", "如果我忘了，我得为你擦桌子", "如果我忘了，我得为你大扫除", "如果我忘了，我得做你的工作一天",
            "如果我忘了，我得替你购物", "如果我忘了，我得替你买菜", "如果我忘了，我得做你喜欢的菜", "如果我忘了，我得为你洗车",
            "如果我忘了，我得为你修剪草坪", "如果我忘了，我得为你换灯泡", "如果我忘了，我得修理你坏的门", "如果我忘了，我得帮你整理",
            "如果我忘了，我得为你装架子", "如果我忘了，我得为你装家具", "如果我忘了，我得为你整理床", "如果我忘了，我得为你做设计",
            "如果我忘了，我得帮你规划日程", "如果我忘了，我得整理你的衣柜", "如果我忘了，我得规划你的日历", "如果我忘了，我得为你做表格",
            "如果我忘了，我得做关于你的演讲", "如果我忘了，我得回答你的任何问题", "如果我忘了，我得为所有事请示", "如果我忘了，我得变得更谦逊",
            "如果我忘了，我得学会耐心", "如果我忘了，我得变得更乐观", "如果我忘了，我得改变生活方式", "如果我忘了，我得改善自己",
            "如果我忘了，我得多学习", "如果我忘了，我得每天进步", "如果我忘了，我得提升技能", "如果我忘了，我得完善自己",
            "如果我忘了，我得自我改革", "如果我忘了，我得更新思维", "如果我忘了，我会成为更好的人", "如果我忘了，我得活得更有责任",
            "如果我忘了，我会更珍惜你", "如果我忘了，我送你100朵玫瑰", "如果我忘了，我买奶茶给你", "如果我忘了，我带你去餐厅",
            "如果我忘了，我陪你玩一整天", "如果我忘了，我当你司机一周", "如果我忘了，我送你惊喜礼物", "如果我忘了，我寄你一张明信片",
            "如果我忘了，我给你画可爱Q版", "如果我忘了，我为你做歌单", "如果我忘了，我为你烤饼干", "如果我忘了，我做你的贴纸",
            "如果我忘了，我为你拍纪念照", "如果我忘了，我录祝贺视频", "如果我忘了，我为你写诗", "如果我忘了，我为你唱摇篮曲"
        ]
    },
    'ja': {
        'apology': [
            "あら!", "うっかり!", "おっと!", "あらあら!",
            "ごめんね!", "すみません!", "失礼!", "お許しを!",
            "あれれ!", "わぁ!", "あちゃ!", "ぷぷっ!",
            "まあ!", "えっ!", "あ!", "おや!",
            "あはは!", "うふふ!", "あはっ!", "えへへ!",
            "やばい!", "やべえ!", "まじか!", "うわー!",
            "なんと!", "おやおや!", "あらまあ!", "あらやだ!",
            "あらら!", "おやまあ!", "おやおや!", "なんてこと!",
            "しまった!", "やっちゃった!", "ミスった!", "やらかした!",
            "ぴえん!", "ぴえーん!", "うえーん!", "がーん!",
            "うわぁ!", "わー!", "わぁー!", "わぁ!",
            "あぁ!", "あー!", "あ〜!", "あれー!",
            "おーい!", "おっと!", "おっとっと!", "おっとお!",
            "やや!", "やー!", "やぁ!", "やぁやぁ!",
            "ええ!", "えー!", "えええ!", "えぇー!",
            "ふえ!", "ふえー!", "ふえーん!", "ふぇっ!",
            "ぎゃ!", "ぎゃー!", "ぎゃあ!", "ぎゃあー!",
            "ひぃ!", "ひー!", "ひぃー!", "ひええ!",
            "うぐ!", "うー!", "うっ!", "うー!",
            "ぐは!", "ぐぅ!", "ぐっ!", "ぐえ!",
            "なんだと!", "なんだ!", "なに!", "なんで!",
            "どうして!", "なんでよ!", "ちょっと!", "ちょっと待って!",
            "ちょい!", "ちょいちょい!", "ちょま!", "ちょいまて!",
            "あらまあ!", "おやまあ!", "あらあら!", "おやおや!",
            "ありゃ!", "ありゃー!", "ありゃりゃ!", "おりゃ!"
        ],
        'reason': [
            "隣の犬がLANケーブルをかじった", "私の猫がキーボードの上に3時間座っていた", "ハトが部屋に飛び込んでパソコンを殴った", "ネズミがマウスをかじった",
            "うちのカメが遅すぎてWi-Fiも遅くなった", "あなたの金魚がお風呂から飛び出した", "外のカエルが3時間鳴き続けた", "テレビが私がタイプする瞬間にCMを再生した",
            "Facebookが超面白い投稿を勧めてきた", "友達が緊急ミームを送ってきた", "Windowsアップデートが聞かずに再起動した", "Netflixが大事な瞬間に自動再生した",
            "Discordが最悪のタイミングで通知を出した", "Chromeタブを開きすぎてラグった", "ターミナルコマンドが意味不明に固まった", "GitHubのマージコンフリクトが喧嘩を売ってきた",
            "Dockerがビルド失敗した、締切直前に", "Alexaがうっかり元カノに電話した", "スマートTVが急に90年代の音楽を流した", "AIアシスタントが突然冗談を言い始めた",
            "嵐のせいでWi-Fiが壁を変に通った", "太陽が眩しすぎてスマホが見えなかった", "大雨で送信ボタンを押すのが怖くなった", "雪がWi-Fiのアンテナを全部覆った",
            "彗星が通り過ぎてネットが止まった", "月が暗すぎて眠くなった", "雲が衛星信号を遮った", "配達員が最悪のタイミングでベルを鳴らした",
            "隣人がカラオケを3時間続けた", "あるジュースのCMに取り憑かれた", "雷が私のルーターに落ちた", "気圧が急に変わった",
            "隣のドリルが鳴り続けた", "工事の音で集中できなくなった", "隣の家のベルが鳴り止まなかった", "弱い回線で音声をダウンロードしていた",
            "Zoom通話が大事な瞬間にクラッシュした", "テキスト打ってる時にプリンターが大きな音を出した", "冷蔵庫が自分で開いた", "エアコンが急に変な音を出した",
            "扇風機が机に落ちた", "電球が肝心な時にチカチカした", "Bluetoothスピーカーが古い信号を拾った", "モバイルバッテリーが急に切れた",
            "充電ケーブルを猫が噛みちぎった", "ノートPCのネジが緩んだ", "ワイヤレスマウスがちょうど電池切れになった", "キーボードのキーが一つ急に壊れた",
            "モニターがぼやけ始めた", "クモがウェブカメラに巣を作った", "マイクが変な音を拾った", "電子レンジが変な音を出し始めた",
            "シーリングファンが大きな音で回り始めた", "給湯器がゴボゴボ鳴った", "食器洗い機が変な音を出した", "蛇口が滴り続けた",
            "浴槽が変な音を出した", "シャワーが自分で出た", "戸棚が自分で開いた", "玄関のドアが急に詰まった",
            "窓が勝手に風を入れた", "クローゼットのドアが開いた", "机が揺れ始めた", "回転椅子が自分で回った",
            "ベッドが急にきしんだ", "ランプがずっとちらついた", "本棚が変な音を出した", "鏡が変に反射した",
            "窓がヒューヒュー鳴り始めた", "テーブルの表面が急に割れた", "床がきしんだ", "壁が変な音を出した",
            "天井がきしみ始めた", "階段が音を立てた", "廊下が急に暗くなった", "風がドアから吹き込んだ",
            "雨が窓の外で激しく打ちつけた", "雷が外で轟いた", "風が大きな音で吹いた", "雪が密に降った",
            "太陽が眩しすぎた", "雲が暗く立ち込めた", "霧が濃く立ち込めた", "蝶が画面を横切った",
            "鳥が外で変に鳴いた", "蜂が窓の周りを飛んだ", "アリが机の上を這った", "ゴキブリが部屋を走った",
            "ハエが私の周りを飛んだ", "蚊が耳元でブンブン鳴った", "クモが天井からぶら下がった", "ヤモリが壁を這った",
            "カエルが部屋に飛び込んだ", "全デバイスが同時にクラッシュした", "全国のネットがダウンした", "私のISPに障害が出た",
            "太陽嵐が信号を妨害した", "モデムが過熱して切れた", "私のパソコンがウイルスに感染した", "ハードディスクがカチカチ鳴り始めた"
        ],
        'action': [
            "私はムーンウォークであなたの方へ歩いている", "私はあなたのために謝罪ラップを歌っている", "私はあなたに犬の絵を贈った", "私はあなたのためにバタージャムトーストを作っている",
            "私はカップ麺を作って持っていく", "私は宇宙ヘルメットを被って謝っている", "私はあなたの一番美しい肖像画を描いた", "私はピザをあなたの家に飛ばしている",
            "私は屋上で一人バレエを踊った", "私はオペラの声で謝罪詩を朗読している", "私は花を運ぶドローンを作った", "私はあなたの名前を彫った木を植えている",
            "私は自分の愚かさについての歌を書いた", "私は片足でヨガをしている", "私は代わりに謝るロボットを作った", "私は冗談を言って謝っている",
            "私は謝罪のダンスカバー動画を作った", "私はキノコと踊っている", "私はあなたの砂像を作っている", "私はレーザーで月に謝罪を書いている",
            "私は1000羽の鳩を育てて謝罪を運ばせる", "私は99人のダンサーと踊っている", "私は街中に謝罪の看板を借りた", "私はハート型のおこげを作っている",
            "私は西湖を走り回っている", "私は花びらで謝罪を書いている", "私は10トンのチョコで謝罪を書いた", "私は100回連続でスクワットしている",
            "私は47の動きのダンスを作った", "私は蛍光塗料で顔を光らせている", "私は鳥の言葉で謝罪を歌っている", "私はバズるハッシュタグ#ごめんね友達を作った",
            "私は爪楊枝で記念碑を建てている", "私は私の愚かさについての3時間の映画を作っている", "私は100枚の違う絵を描いた", "私はあなたの家まで10km歩いている",
            "私はタイタニックを謝罪バージョンで演じている", "私は謝罪を100回録音した", "私は飛行機の煙で謝罪を書いている", "私は50匹の犬に謝罪を吠えさせた",
            "私はふわふわの羊の衣装で踊っている", "私は謝罪の形の花火を準備している", "私は10000枚のドミノを並べている", "私は湖面に謝罪を描いている",
            "私は100ページの謝罪塗り絵を塗った", "私は古い街でパルクールしている", "私は謝罪の歌を口ずさんでいる", "私はTシャツに謝罪をプリントした",
            "私は謝罪の形のケーキを作っている", "私は謝罪の看板を持ってマラソンしている", "私は謝罪ミーム集を作った", "私は謝罪を建物に投影している",
            "私は謝罪パーティーを開いている", "私は100枚の皿に謝罪を書いた", "私はサッカー応援のように謝罪を叫んでいる", "私は謝罪の花の車を飾っている",
            "私は100本のろうそくで謝罪を並べた", "私はグラウンドに光の輪を作っている", "私は凧で空に謝罪を書いている", "私は砂で謝罪を綴っている",
            "私は謝罪看板を持って公園を走っている", "私はあなたの名前を彫った砂のお城を作っている", "私はLEDで謝罪を描いている", "私は20の違う声で謝罪を録音した",
            "私は私のミスのための追悼式を開いている", "私はサーカスの謝罪を演じている", "私は謝罪の形の花火を打ち上げている", "私はあなたの粘土像を作っている",
            "私は私のミスについてのミュージカルを上演している", "私は紙の謝罪タワーを作っている", "私は謝罪の壁画を描いている", "私は水人形劇で謝罪を演じている",
            "私は謝罪の絵画展を開いている", "私は謝罪の短編アニメを作っている", "私は謝罪の交響曲を作曲している", "私は24/7謝罪をライブ配信している",
            "私は空に謝罪のビームを照射している", "私はアート展を開催している", "私は謝罪の花火パーティーを開いている", "私は謝罪フェスティバルを開催している",
            "私は川にランタンを流している", "私は謝罪のプレゼンをしている", "私は謝罪のバレエを踊っている", "私は自宅の壁に謝罪の絵を描いている",
            "私は謝罪のカーペットを織っている", "私は謝罪の書道をしている", "私はあなたの名前を木彫りしている", "私は謝罪のマフラーを編んでいる",
            "私は謝罪を綴る折り紙を折っている", "私はバルコニーを謝罪看板にしている", "私は謝罪の手紙付きの贈り物を包んでいる", "私は巨大な花束を準備している",
            "私はあなたの家に100個のキャンディーを持っていく", "私は歩道にチョークで絵を描いている", "私は謝罪の形のシャボン玉を吹いている", "私は1000羽の折り鶴を折っている",
            "私は思い出の写真ビデオを作っている", "私はあなたのかわいいちびキャラを描いている", "私はあなたのためのヒーリングプレイリストを作っている", "私はハート型のクッキーを焼いている"
        ],
        'promise': [
            "次回は世界中に思い出させる", "アラームを10個セットする", "ペンで手にリマインダーを書く", "犬にリマインドを頼んだ",
            "毎日メッセージを送る、用が無くても", "リマインドするオウムを送る", "リマインドする人を雇う", "心で覚える、たぶん",
            "ヘナで額にリマインダーをタトゥーする", "家中にポストイットを貼る", "家族全員にリマインドさせる", "すべてを追跡するスプレッドシートを作る",
            "5分ごとに着信音を鳴らす", "お金に書いて毎日見る", "Alexaに毎朝リマインドさせる", "あなたをスマホのウィジェットにする",
            "リマインダーを録音して24/7再生する", "毎日TikTokを作る", "プライベートDiscordグループを作る", "リマインダー専用AIボットを作る",
            "鉛筆にリマインダーを彫る", "毎日自動メールを送る", "全社員に電話でリマインドさせる", "1年分の追跡ボードを作る",
            "点字を学んでリマインダーを彫る", "あらゆる隅にリマインダーを置く", "毎日FaceTimeでリマインドする", "週刊ポッドキャストを作る",
            "石にリマインダーを彫る", "リマインダーへのQRコードを作る", "リマインダー入りのギフトを送る", "煙ペンでリマインダーを書く",
            "リマインダーのラップを作る", "リマインダーのブレスレットを作る", "100通りのリマインド方法をリストする", "リマインダーを運ぶ鳥を送る",
            "毎朝手にリマインダーを書く", "リマインダーゲームを作る", "リマインダーウェブサイトを作る", "ロボットにリマインダーを唱えさせる",
            "Tシャツにリマインダーをプリントする", "バスルームの鏡にリマインダーを貼る", "リマインダーを壁紙にする", "毎日鏡の前で自己リマインドする",
            "リマインダーを着信音にする", "リマインダーをBGMに設定する", "ドアにリマインダーを書く", "壁中にリマインダーを貼る",
            "毎日同じ時間にリマインドする", "自分のリマインダーアプリを作る", "ビーチの砂にリマインダーを描く", "毎日リマインダー動画を作る",
            "常にリマインダーストーリーを投稿する", "リマインダー専用チャットグループを作る", "ポップソングでアラームをセットする", "リマインダーを100言語に翻訳する",
            "カウントダウンカレンダーを作る", "毎朝7時に電話する", "毎週手書きの手紙を送る", "特別な封筒を作る",
            "メモ帳を買う", "あなたと書面の誓約書にサインする", "あなたに特別な料理を作る", "あなたにブレスレットをあげる",
            "謝罪のラブレターを書く", "100言語でリマインダーを言うために学ぶ", "毎朝リマインダーを歌う", "リマインダーの曲を作曲する",
            "家中にポスターを貼る", "カップにリマインダーをプリントする", "茶碗にリマインダーをプリントする", "服にリマインダーを刺繍する",
            "リマインダーボックスを作る", "誓いのビデオを撮る", "約束の日記をつける", "約束の壁を作る",
            "リマインダーのネックレスを着ける", "リマインダーをいつも持ち歩く", "リマインダーを抱いて寝る", "リマインダーを暗記する",
            "一生リマインダーを覚える", "リマインダーと共に生きる", "リマインダーと共に呼吸する", "リマインダーに没頭する",
            "リマインダーと一体化する", "生きるリマインダーになる", "毎日手にリマインダーを描く", "リマインダーを人生の目的にする",
            "全ての思考をリマインダーに捧げる", "リマインダーを宝物のように扱う", "毎日リマインダーで瞑想する", "毎晩リマインダーの夢を見る",
            "ずっとリマインダーを考える", "みんなにリマインダーを話す", "家族にリマインダーを教える", "リマインダーを広く広める",
            "リマインダーを有名にする", "リマインダーを日記に書く", "リマインダーを永遠に保つ", "あらゆる手段でリマインダーを守る"
        ],
        'consequence': [
            "もし忘れたら、カピバラを贈る", "もしまた忘れたら、枕で叩いていい", "もし忘れたら、大勢の前で歌う", "もし忘れたら、SNSで公開告白する",
            "もし忘れたら、誕生日の看板を借りる", "もし忘れたら、1時間ダンスカバーする", "もし忘れたら、花畑全部贈る", "もし忘れたら、ニックネームを「ドジっ子」に変えていい",
            "もし忘れたら、アイス1杯食べきる", "もし忘れたら、アニメキャラの公開コスプレ", "もし忘れたら、ステージで本音を言う", "もし忘れたら、アバターを赤ちゃん写真に変えていい",
            "もし忘れたら、あなたの靴を1日履く", "もし忘れたら、ブラウザ履歴を全消去する", "もし忘れたら、謝罪看板を持って街を歩く", "もし忘れたら、手書き謝罪100ページ送る",
            "もし忘れたら、Facebookを1ヶ月ロックされる", "もし忘れたら、変な服でイベントに行く", "もし忘れたら、コードを無料で教える", "もし忘れたら、公園を10km歩く",
            "もし忘れたら、私の素敵な写真を全部消されていい", "もし忘れたら、1週間家事をする", "もし忘れたら、「ごめんなさい」を1000回書く", "もし忘れたら、好きなプレゼントを選んでいい",
            "もし忘れたら、あなたの家の周りを走る", "もし忘れたら、クラシックカーを借りて謝罪を歌う", "もし忘れたら、私に挑戦できる", "もし忘れたら、あなたのライブに出る",
            "もし忘れたら、美味しい食事を1回逃す", "もし忘れたら、1日あなたの言いなりになる", "もし忘れたら、私を知らないふりしていい", "もし忘れたら、1日あなたの家の前に立つ",
            "もし忘れたら、自画像にサインする", "もし忘れたら、私の写真をアバターに使っていい", "もし忘れたら、1日ボランティアする", "もし忘れたら、1週間スマホを使わない",
            "もし忘れたら、私の全友達に電話していい", "もし忘れたら、1週間好物を食べない", "もし忘れたら、1週間使いっぱしりをする", "もし忘れたら、縞模様パジャマで学校に行く",
            "もし忘れたら、また枕で叩かれる", "もし忘れたら、毎晩おやすみを言う", "もし忘れたら、1時間あなたの話を聞く", "もし忘れたら、1日助手になる",
            "もし忘れたら、あなたの言うことを全部聞く", "もし忘れたら、1週間料理を作る", "もし忘れたら、食器を洗う", "もし忘れたら、洗濯する",
            "もし忘れたら、家を掃除する", "もし忘れたら、テーブルを拭く", "もし忘れたら、大掃除する", "もし忘れたら、1日仕事を肩代わりする",
            "もし忘れたら、買い物代行する", "もし忘れたら、食材を買いに行く", "もし忘れたら、好きな料理を作る", "もし忘れたら、車を洗う",
            "もし忘れたら、芝を刈る", "もし忘れたら、電球を変える", "もし忘れたら、壊れたドアを直す", "もし忘れたら、片付けを手伝う",
            "もし忘れたら、棚を取り付ける", "もし忘れたら、家具を組み立てる", "もし忘れたら、ベッドを整える", "もし忘れたら、デザインしてあげる",
            "もし忘れたら、スケジュールを立てる", "もし忘れたら、クローゼットを整理する", "もし忘れたら、カレンダーを計画する", "もし忘れたら、追跡シートを作る",
            "もし忘れたら、あなたについてプレゼンする", "もし忘れたら、何でも質問に答える", "もし忘れたら、全てのことで許可を取る", "もし忘れたら、もっと謙虚になる",
            "もし忘れたら、忍耐を学ぶ", "もし忘れたら、もっと前向きになる", "もし忘れたら、生活を変える", "もし忘れたら、自分を磨く",
            "もし忘れたら、もっと学ぶ", "もし忘れたら、毎日成長する", "もし忘れたら、スキルを上げる", "もし忘れたら、自分を完成させる",
            "もし忘れたら、自己改革する", "もし忘れたら、考え方を新しくする", "もし忘れたら、より良い人になる", "もし忘れたら、責任を持って生きる",
            "もし忘れたら、あなたをもっと大切にする", "もし忘れたら、バラ100本贈る", "もし忘れたら、タピオカを買う", "もし忘れたら、レストランに連れて行く",
            "もし忘れたら、1日中一緒に遊ぶ", "もし忘れたら、1週間運転手になる", "もし忘れたら、サプライズプレゼント", "もし忘れたら、ハガキを送る",
            "もし忘れたら、可愛いちびキャラを描く", "もし忘れたら、プレイリストを作る", "もし忘れたら、クッキーを焼く", "もし忘れたら、あなたの顔のステッカーを作る",
            "もし忘れたら、思い出の写真を撮る", "もし忘れたら、お祝いビデオを撮る", "もし忘れたら、詩を書く", "もし忘れたら、子守唄を歌う"
        ]
    }
}

def generate(lang='en'):
    d = DATA[lang]
    l = LANG[lang]
    
    apology = random.choice(d['apology'])
    reason = random.choice(d['reason'])
    action = random.choice(d['action'])
    promise = random.choice(d['promise'])
    consequence = random.choice(d['consequence'])
    
    box = f"""
╔══════════════════════════════════════════════════════════════════╗
║                                                                  ║
║  {apology}!                                                     ║
║                                                                  ║
║  {l['reason_label']}: {reason}                                  ║
║                                                                  ║
║  {l['action_label']}: {action}                                    ║
║                                                                  ║
║  {l['promise_label']}: {promise}                                ║
║                                                                  ║
║  {l['consequence_label']}: {consequence}                         ║
║                                                                  ║
╚══════════════════════════════════════════════════════════════════╝
"""
    return box

def main():
    print("=" * 65)
    print("  🎪 FUN APOLOGY GENERATOR 🎪")
    print("=" * 65)
    print()
    print("Select language / Chọn ngôn ngữ / 选择语言 / 言語を選択:")
    print("  1. English 🇺🇸")
    print("  2. Tiếng Việt 🇻🇳")
    print("  3. 中文简体 🇨🇳")
    print("  4. 日本語 🇯🇵")
    print()
    
    choice = input("Enter 1-4 (default 1): ").strip()
    lang_map = {'1': 'en', '2': 'vi', '3': 'zh', '4': 'ja'}
    lang = lang_map.get(choice, 'en')
    
    l = LANG[lang]
    
    print()
    print("=" * 65)
    print(f"  {l['title']}")
    print("=" * 65)
    print()
    print(l['intro'])
    print()
    
    while True:
        input(l['prompt'])
        print()
        print(generate(lang))

if __name__ == "__main__":
    main()
